
GET http://localhost:3100/api/getAllUsers
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFiaGluYXZmZ0Bob3RtYWlsLmNvbSIsImlhdCI6MTcwNzIyMjc4NywiZXhwIjoxNzA3MjIyODQ3fQ.8vyWvYV3s1950IV6vyHcEQRuiFUf4PCo6riS3nBOCVU
###
POST http://localhost:3100/api/login
Content-Type:application/json

{
    "email":"a@k.com",
    "password":"Pass@123"
}
###
POST http://localhost:3100/api/localhost:3100/api/register
Content-Type:application/json

{   
    "userName":"ak",
    "email":"ak@gmail.com",
    "password":"Pass@123"
}